### ISSUE TITLE
[Error  :WeatherTweaks] Failed to change fog: System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by CoolLKKPS** [AndreyMrovol/LethalWeatherTweaks#18]
[Error  : Loadstone(Harmony)] The assembly "WeatherTweaks" has patched the method "Void SpawnOutsideHazards()" with a transpiler using "System.Collections.Generic.IEnumerable\`1[HarmonyLib.CodeInstruction] SpawnOutsideHazardsPatch(System.Collections.Generic.IEnumerable\`1[HarmonyLib.CodeInstruction])", which we also modify. Unexpected behaviour may occur

[Error  :WeatherTweaks] Failed to change fog: System.NullReferenceException: Object reference not set to an instance of an object
  at WeatherTweaks.BasegameWeatherPatch.ChangeFog (System.Single meanFreePath) [0x0000c] in <2e4b076e21a044408ed1781dec5515b8>:IL_000C
[Error  :WeatherTweaks] Landing at 8 Titan with weather {"Name":"Stormy","weatherType":2,"Weathers":[2],"Type":0}

**Comment by CoolLKKPS** [comment]
@AndreyMrovol

**Comment by CoolLKKPS** [comment]
and also i bring another issue about LLL: https://thunderstore.io/c/lethal-company/p/Zhelderon/LethalLevelLoaderFixed
this can run with v50 actually but the page are not found now, *idk why LLL author really care about the license and there's no other custom levelloader are better than LLL, so i will save that LLL version for better gaming experience*
***in my opinion, LLL should update rn***

**Comment by AndreyMrovol** [comment]
@CoolLKKPS 

> [Error : Loadstone(Harmony)] The assembly "WeatherTweaks" has patched the method "Void SpawnOutsideHazards()" with a transpiler using "System.Collections.Generic.IEnumerable`1[HarmonyLib.CodeInstruction] SpawnOutsideHazardsPatch(System.Collections.Generic.IEnumerable`1[HarmonyLib.CodeInstruction])", which we also modify. Unexpected behaviour may occur

I'll look at this, thanks for reporting


> [Error :WeatherTweaks] Failed to change fog: System.NullReferenceException: Object reference not set to an instance of an object
at WeatherTweaks.BasegameWeatherPatch.ChangeFog (System.Single meanFreePath) [0x0000c] in <2e4b076e21a044408ed1781dec5515b8>:IL_000C

This is sometimes happening, I'll change it to be a warning rather than error - it's not impacting the game in any way


> [Error :WeatherTweaks] Landing at 8 Titan with weather {"Name":"Stormy","weatherType":2,"Weathers":[2],"Type":0}

I've added that because I got a few .logs without debug logging and I need *some* information on where to look for bugs, this error can be safely ignored, it's for me only 👍 


> and also i bring another issue about LLL: https://thunderstore.io/c/lethal-company/p/Zhelderon/LethalLevelLoaderFixed
this can run with v50 actually but the page are not found now, idk why LLL author really care about the license and there's no other custom levelloader are better than LLL, so i will save that LLL version for better gaming experience
in my opinion, LLL should update rn

It was taken down because it was an ugly reupload of LLLFixed, it was running the v49 version of LLL on v50 - the *actual* v50 LLL is still in the works and *actually* changing a ton of stuff, so this time is for all the creators to port their things

**Comment by CoolLKKPS** [comment]
> It was taken down because it was an ugly reupload of LLLFixed, it was running the v49 version of LLL on v50 - the actual v50 LLL is still in the works and actually changing a ton of stuff, so this time is for all the creators to port their things

thx to let me know that, yea bc that fix version didn't throw any error, so i thought that can work so i didn't think much deeper

and thx for ur reply :)

**Comment by AndreyMrovol** [comment]
> [Error : Loadstone(Harmony)] The assembly "WeatherTweaks" has patched the method "Void SpawnOutsideHazards()" with a transpiler using "System.Collections.Generic.IEnumerable1[HarmonyLib.CodeInstruction] SpawnOutsideHazardsPatch(System.Collections.Generic.IEnumerable1[HarmonyLib.CodeInstruction])", which we also modify. Unexpected behaviour may occur

Alright, i've checked: seems like there's not gonna be any conflicts between the two methods:

- https://github.com/AdalynBlack/Loadstone/blob/2627558dcad1db60914801363130346548d6f67e/Patches/RoundManagerPatches.cs#L165-L187
- https://github.com/AndreyMrovol/LethalWeatherTweaks/blob/5ec67a0713cef5280cb0899ebf9847a6844f0dd9/WeatherTweaks/Patches/SpawnOutsideHazards.cs#L15-L41
