### ISSUE TITLE
Due to the transfer, the weather in the terminal is not the same

### ISSUE THREAD

**Issue by Paradox75831004** [AndreyMrovol/LethalWeatherTweaks#5]
I'm not sure exactly, but because of the translation, it shows the exact weather and it doesn't matter what the weather is written on the monitor...

I think the problem is on my side that I have installed too many mods

018d7d8c-7252-8a67-8364-fd87914208f4

**Comment by AndreyMrovol** [comment]
Hey, thanks for reporting the issue - I'm gonna check what's happening.

**Comment by AndreyMrovol** [comment]
From what i've found:

- Info screen shows true weather because of [CorporateRestructureWeather](https://thunderstore.io/c/lethal-company/p/CatsArmy/CorporateRestructureWeather/) - this is a functionality that's included with my mod (colored weather display)
- Terminal shows prices because of [MoonsPriceDisplay](https://thunderstore.io/c/lethal-company/p/Gloveman23/MoonPriceDisplay/), which overrides LLL (and my mod) from inserting custom weathers into the list (https://github.com/Gloveman23/MoonPriceDisplay/blob/9b53f795c762fec30a3dc33242b7bb360e6ebc7b/Plugin.cs#L63)
- Russian translation mods completely override LLL's terminal display, and my mod won't display its weathers because of it (unfortunately)
- GeneralImprovements monitor always display true weather (in your case monitor 1 and 2)

Disabling these mods allowed uncertain weathers to show up.

**Comment by Paradox75831004** [comment]
I thought so, thanks for the explanation. Will this be fixed in the future? Or just disable mods and play without them...

**Comment by Paradox75831004** [comment]
I've just been looking for a very long time for a mod that somehow hid the weather, allows you to complicate the gameplay and make forays into different weather more often

**Comment by AndreyMrovol** [comment]
Hey, I'll see what I can do, but the translation mod inserts itself in such a way that my mod isn't even executed:
![image](https://github.com/AndreyMrovol/LethalWeatherTweaks/assets/32998721/910cc5f0-dacf-4423-843b-4cc2c6d00608)
![image](https://github.com/AndreyMrovol/LethalWeatherTweaks/assets/32998721/f9aad068-3498-4b6e-a58a-5a7889242de6)

**Comment by AndreyMrovol** [comment]
Okay, I think i managed to find the issue and how to solve it:
[RTLC Russian Translation Mods](https://thunderstore.io/c/lethal-company/p/Hayrizan/RTLC_Russian_Translation_Mods/) patches `LoadNewNode` method as a prefix [(code snippet)](https://thunderstore.io/c/lethal-company/p/Hayrizan/RTLC_Russian_Translation_Mods/source/#:~:text=%5BHarmonyPrefix%5D%0A%09%09private%20static%20bool%20Prefix(ref%20TerminalNode%20node)%0A%09%09%7B%0A%09%09%09string%20text%20%3D%20Translator.TranslateNode(((Object)node).name%2C%20node.displayText)%3B%0A%09%09%09if%20(text%20!%3D%20null)%0A%09%09%09%7B%0A%09%09%09%09node.displayText%20%3D%20text%3B%0A%09%09%09%7D%0A%09%09%09return%20true%3B%0A%09%09%7D), which skips LethalLevelLoader's method in its entirety, causing no modded weathers to show up. 

When I've manually unpatched this, all modded weathers (and their translations) showed up, but the translations were mostly broken.
![image](https://github.com/AndreyMrovol/LethalWeatherTweaks/assets/32998721/59c41239-8265-40b9-947b-c04dc9bd24f4)

![image](https://github.com/AndreyMrovol/LethalWeatherTweaks/assets/32998721/ab92a44b-a881-47f0-be76-78e018262e03)

Moreover, I saw that this is a wider issue with translation mod as a whole [(example)](https://discord.com/channels/1050842181616816219/1187665162929451048/1204263736312074312).

@Paradox75831004 Could you get in contact with translation mod's author and suggest changing `Prefix` to `Postfix` method? I think this wouldn't break translations *and* it would make my (and many other) mods compatible.

**Comment by AndreyMrovol** [comment]
I've attemted some fixes on my end:

- this mod will always replace vanilla's `[planetTime]` placeholder with empty string
- this mod's `SetMapScreenInfoToCurrentLevel` patch has the highest priority, so it will override other mods trying to apply the same functionality.
